# Main configuration file for the bomb arena type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 900
lobbyTime: 70
maxDeaths: 990
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: true
cashReward: 100
rewards:
- GOLD_INGOT, 3
- TNT, 1
