# Main configuration file for the conquest arena type
# https://github.com/MineSworn/UltimateArena/wiki/Configuration

gameTime: 1200
lobbyTime: 180
maxDeaths: 900
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: true
cashReward: 100
rewards:
- GOLD_INGOT, 3
- TNT, 1
