# Main configuration file for the koth arena type
# https://github.com/MineSworn/UltimateArena/wiki/Configuration

gameTime: 1200
lobbyTime: 80
maxDeaths: 900
allowTeamKilling: true
rewardBasedOnXp: true
countMobKills: false
cashReward: 100
maxPoints: 60
rewards:
- GOLD_INGOT, 3
- TNT, 1
