# Main configuration file for the pvp arena type
# http://dev.bukkit.org/bukkit-plugins/ultimatearena/pages/configuration/

gameTime: 600
lobbyTime: 90
maxDeaths: 3
allowTeamKilling: false
countMobKills: false
rewardBasedOnXp: true
cashReward: 100
rewards:
- GOLD_INGOT, 3
- TNT, 1
